# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ikaSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ikaSDK
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'PromisesSwift'
	pod 'SDWebImage'
end
